# Generated by Django 3.1.7 on 2021-03-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_auto_20210311_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitchen',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='slug',
        ),
    ]
