# Generated by Django 3.1.7 on 2021-03-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_auto_20210312_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='days',
            field=models.ManyToManyField(related_name='days', to='kitchen.Day'),
        ),
    ]
